# ===========================================
# ORION USER SERVICE - application.yml (dev/docker)
# ===========================================

server:
  port: ${USER_SERVICE_PORT:8092}

spring:
  application:
    name: ${SERVICE_NAME:orion-user}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # MongoDB Configuration - Uses centralized variables
  data:
    mongodb:
      uri: ${MONGODB_URI}

  # Docker Compose (disabled by default)
  docker:
    compose:
      enabled: false

# External Services Configuration - All from .env
orion:
  services:
    program-service-url: ${PROGRAM_SERVICE_URL}
    connection-timeout: ${SERVICE_CONNECTION_TIMEOUT:5s}
    read-timeout: ${SERVICE_READ_TIMEOUT:10s}
    max-retries: ${SERVICE_MAX_RETRIES:3}
    retry-delay: ${SERVICE_RETRY_DELAY:500ms}
    failure-rate-threshold: ${SERVICE_FAILURE_RATE:50.0}
    minimum-number-of-calls: ${SERVICE_MIN_CALLS:5}
    wait-duration-in-open-state: ${SERVICE_CIRCUIT_WAIT:30s}
    strict-email-validation: ${USER_STRICT_EMAIL_VALIDATION:false}
    require-strong-password: ${USER_REQUIRE_STRONG_PASSWORD:true}

gateway:
  service:
    token: ${GATEWAY_SERVICE_TOKEN:dev-token-unibague-orion}

# Logging Configuration - Uses centralized variables
logging:
  level:
    com.unibague.gradework: ${LOG_LEVEL_USER:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.springframework.data.mongodb: ${MONGODB_LOG_LEVEL:WARN}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
    root: ${LOGGING_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# ===========================================
# DEVELOPMENT PROFILE - Minimal overrides
# ===========================================
spring:
  config:
    activate:
      on-profile: dev

# Development-specific settings (if needed)
logging:
  level:
    com.unibague.gradework: DEBUG

---
# ===========================================
# DOCKER PROFILE - Minimal overrides
# ===========================================
spring:
  config:
    activate:
      on-profile: docker

# All Docker configuration comes from environment variables
# No hardcoded values here

---
# ===========================================
# PRODUCTION PROFILE - Minimal overrides
# ===========================================
spring:
  config:
    activate:
      on-profile: prod

# Production-specific settings
logging:
  level:
    root: WARN
    com.unibague.gradework: INFO